# Generated by Django 5.2.4 on 2025-07-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaintTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='original_images/')),
                ('clicked_x', models.IntegerField(blank=True, null=True)),
                ('clicked_y', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(default='#ff0000', max_length=7)),
                ('result_image', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
